import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  root: { display: 'flex', flexDirection: 'column', height: '100vh', background: '#0a0f1e', color: '#e2e8f0', fontFamily: 'ui-monospace, "SF Mono", Menlo, monospace', fontSize: 13 },
  header: { display: 'flex', alignItems: 'center', gap: 16, padding: '12px 20px', borderBottom: '1px solid #1e293b', background: '#0d1424', flexShrink: 0 },
  headerTitle: { fontSize: 16, fontWeight: 700, color: '#4f8ef7', letterSpacing: '-0.01em' },
  headerSub: { color: '#64748b', fontSize: 12 },
  tabs: { display: 'flex', gap: 4, marginLeft: 'auto' },
  tab: { padding: '5px 14px', borderRadius: 6, border: '1px solid #1e293b', background: 'transparent', color: '#94a3b8', cursor: 'pointer', fontSize: 12 },
  tabActive: { background: '#1e293b', color: '#e2e8f0', borderColor: '#334155' },
  toolbar: { display: 'flex', gap: 8, padding: '8px 16px', borderBottom: '1px solid #1e293b', background: '#0d1424', flexShrink: 0, flexWrap: 'wrap' },
  searchInput: { flex: 1, minWidth: 160, padding: '6px 10px', background: '#1e293b', border: '1px solid #334155', borderRadius: 6, color: '#e2e8f0', fontSize: 12, outline: 'none' },
  select: { padding: '6px 10px', background: '#1e293b', border: '1px solid #334155', borderRadius: 6, color: '#e2e8f0', fontSize: 12, outline: 'none', cursor: 'pointer' },
  body: { flex: 1, overflow: 'hidden', position: 'relative' },
  loading: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', color: '#64748b', fontSize: 14 },
  graphArea: { position: 'relative', height: '100%' },
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, maxWidth: 800 },
  statCard: { display: 'flex', flexDirection: 'column', gap: 4, padding: '14px 16px', background: '#0d1424', border: '1px solid #1e293b', borderRadius: 8 },
  statValue: { fontSize: 28, fontWeight: 700, color: '#4f8ef7', lineHeight: 1 },
  statLabel: { fontSize: 11, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 },
  kindRow: { display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 6 },
  kindBadge: { display: 'flex', alignItems: 'center', gap: 6, padding: '3px 8px', borderRadius: 4, border: '1px solid', fontSize: 11 },
  kindCount: { color: '#94a3b8', fontSize: 11 },
  detailPanel: { position: 'absolute', top: 12, right: 12, width: 340, maxHeight: 'calc(100% - 24px)', overflowY: 'auto', background: '#0d1424', border: '1px solid #1e293b', borderRadius: 10, padding: 16, boxShadow: '0 8px 32px rgba(0,0,0,0.5)', zIndex: 10 },
  detailHeader: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 },
  kindChip: { padding: '2px 8px', borderRadius: 4, border: '1px solid', fontSize: 11, flexShrink: 0 },
  detailName: { fontWeight: 700, color: '#f1f5f9', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', flex: 1 },
  closeBtn: { background: 'none', border: 'none', color: '#64748b', cursor: 'pointer', fontSize: 14, padding: '0 4px', lineHeight: 1, flexShrink: 0 },
  detailMeta: { display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
  metaItem: { fontSize: 11, color: '#94a3b8', background: '#1e293b', padding: '2px 8px', borderRadius: 4 },
  signature: { background: '#1a2540', padding: '8px 10px', borderRadius: 6, fontSize: 11, color: '#7dd3fc', margin: '8px 0', overflowX: 'auto', whiteSpace: 'pre-wrap', wordBreak: 'break-all' },
  docstring: { fontSize: 12, color: '#94a3b8', lineHeight: 1.5, margin: '8px 0' },
  edgeSection: { marginTop: 12 },
  edgeSectionTitle: { fontSize: 11, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 },
  edgeRow: { display: 'flex', alignItems: 'center', gap: 8, width: '100%', padding: '5px 8px', background: 'none', border: '1px solid #1e293b', borderRadius: 5, color: '#e2e8f0', cursor: 'pointer', marginBottom: 4, textAlign: 'left', fontSize: 12 },
  edgeNodeName: { flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: '#cbd5e1' },
  edgeFile: { fontSize: 10, color: '#475569', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: 100 },
  legend: { position: 'absolute', bottom: 16, left: 16, display: 'flex', flexWrap: 'wrap', gap: 8, background: 'rgba(13,20,36,0.85)', padding: '8px 12px', borderRadius: 8, border: '1px solid #1e293b', backdropFilter: 'blur(4px)', zIndex: 5 },
  legendItem: { display: 'flex', alignItems: 'center', gap: 5, fontSize: 11, color: '#94a3b8' },
  legendDot: { width: 8, height: 8, borderRadius: '50%', flexShrink: 0 },
};
